name: CI e CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  docker_image_name: walvesribeiro/ricky-morty-app:${{github.run_number}}
jobs:
  CI:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5.0.0
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.docker_image_name }}
          walvesribeiro/ricky-morty-app:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    environment: github-pages
    steps:
    - name: Checkout para o repositório
      uses: actions/checkout@v3
    
    - name: Acionando o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Instalando as Dependencias
      run: npm install
  
    - name: Build e Deploy para GitHub Pages
      uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
      with:
        path: docs/${{ github.event.repository.name }}                           
        build_command: npm run build -- --base-href=/${{ github.event.repository.name }}/
